### ISSUE TITLE
Error loading Plugin State from Layout

### ISSUE THREAD

**Issue by mengchaoheng** [arplaboratory/GeomInertiaEstimator#3]
after run
```
roscd geom_inertia_estimator/
rosrun plotjuggler PlotJuggler -l config/PlotJuggler_Layout.xml
```
terminal:
```
Couldn't find executable named PlotJuggler below /opt/ros/noetic/share/plotjuggler
```
I fix it by change `PlotJuggler` to `plotjuggler`
```
rosrun plotjuggler plotjuggler -l config/PlotJuggler_Layout.xml
```
and new problem is plotjuggler don't have figure and terminal is :
```
~/catkin_ws/src/GeomInertiaEstimator$ rosrun plotjuggler plotjuggler -l config/PlotJuggler_Layout.xml
Loading compatible plugins from directory:  "/opt/ros/noetic/lib/plotjuggler"
"libDataLoadCSV.so is a DataLoader plugin"
"libDataLoadMCAP.so is a DataLoader plugin"
"libDataLoadULog.so is a DataLoader plugin"
"libDataStreamSample.so is a DataStreamer plugin"  ...disabled, unless option -t is used
"libDataStreamUDP.so is a DataStreamer plugin"
"libDataStreamWebSocket.so is a DataStreamer plugin"
"libDataStreamZMQ.so is a DataStreamer plugin"
"libParserDataTamer.so is a MessageParser plugin"
"libParserROS1.so is a MessageParser plugin"
"libParserROS2.so is a MessageParser plugin"
"libProtobufParser.so is a MessageParser plugin"
"libPublisherCSV.so is a StatePublisher plugin"
Type conversion already registered from type QString to type QwtText
"libToolboxFFT.so is a Toolbox plugin"
"libToolboxLuaEditor.so is a Toolbox plugin"
Type conversion already registered from type QString to type QwtText
"libToolboxQuaternion.so is a Toolbox plugin"
Number of plugins loaded:  14 

Loading compatible plugins from directory:  "/opt/ros/noetic/lib/plotjuggler_ros"
Number of plugins loaded:  0 

Loading compatible plugins from directory:  "/home/parallels/mavros_ws/devel/lib/plotjuggler_ros"
Number of plugins loaded:  0 

Loading compatible plugins from directory:  "/home/parallels/catkin_ws/devel/lib/plotjuggler_ros"
Number of plugins loaded:  0 

Loading compatible plugins from directory:  "/home/parallels/hunter_ws/devel/lib/plotjuggler_ros"
Number of plugins loaded:  0 

Loading compatible plugins from directory:  "/home/parallels/rotors_ws/devel/lib/plotjuggler_ros"
Number of plugins loaded:  0 

Loading compatible plugins from directory:  "/home/parallels/.local/share/PlotJuggler"
Number of plugins loaded:  0 


```

**Comment by mengchaoheng** [comment]
`The method xmlSaveState() must return a node like this <plugin ID="PluginName" `

**Comment by vwueest** [comment]
They have made significant changes to plotjuggler since our release 5 years ago where we used ROS melodic. Which ROS version were you using? It would be helpful for an update of the instructions. 

I will update the run instructions. Unfortunately, I don't have access to a computer with ROS for a few months, so I can't create a new layout file. I recommend checking out [their website](https://plotjuggler.io/) for instructions on how to use the software if you're new to it. It is a great piece of software that is rather intuitive. You can then plot the estimates by plotting the messages in the topic `/quadrotor/geom_inertia_estimator/param_estimates/`.

**Comment by mengchaoheng** [comment]
I have solved this problem and I will post the latest solution here. Thanks again for your reply.

**Comment by mengchaoheng** [comment]
The conversion of px4 from ned to enu coordinate system is to swap x and y, and then reverse the setting of z. Since I cannot judge the specific details of the data set(config/lissajous_trajectory.bag ), I cannot give the exact data flow of px4 to your project.

**Comment by vwueest** [comment]
Thanks, would be highly appreciated!

**Comment by mengchaoheng** [comment]
A new [fork](https://github.com/mengchaoheng/GeomInertiaEstimator.git) of this is update.

**Comment by vwueest** [comment]
Thanks for the update! I will pull in the working Plotjuggler layouts
